### ISSUE TITLE
Activity' has no attribute 'query'

### ISSUE THREAD

**Issue by mainak-singulr** [kvesteri/postgresql-audit#112]
Hi team, 
I am using below sample code to test postgresql-audit. When running below code i am facing below 2 issues: 
1. Audit entries are not getting created in activity table. 
2. Activity.query.first() is returning below error. 

```py
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-8095c5293cc0>", line 1, in <module>
    Activity.query.first()
AttributeError: type object 'Activity' has no attribute 'query'
```

Attaching code below. 

```py
import random

from postgresql_audit import versioning_manager
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import session

from common.connectors.db_executor import DBUpdateExecutor
from store.connectors.sqlalchemy_metadata import Base

versioning_manager.init(Base)

class Article(Base):
    __tablename__ = 'article'
    __versioned__ = {}
    id = Column(Integer, primary_key=True)
    name = Column(String)

article = Article(id = random.randint(0, 100), name='Some article')
executor = DBUpdateExecutor()
_ = executor.get_db_connection()
executor.insert_record(article)


Activity = versioning_manager.activity_cls

activity = Activity.query.first()
activity.id             # 1
activity.table_name     # 'article'
activity.verb           # 'insert'
activity.old_data       # {}
activity.changed_data   # {'id': '1', 'name': 'Some article'}
```

Versions: 
postgresql-audit = "^0.17.1"
SQLAlchemy = "1.4.47"
cc: @kvesteri

**Comment by tvuotila** [comment]
`Activity.query` is flask_sqlalchemy extension. Thus, you probably need to do:
```
from sqlalchemy import select

activity = session.scalars(select(Activity)).first()
# Or: activity = session.query(Activity).first()
```

You also need to apply versioning to the table, with something like:
```
session.execute('''SELECT audit_table('article')''')
```

**Comment by mainak-singulr** [comment]
@tvuotila 
Thanks for prompt response. 
On executing code mentioned in `, i am getting error for no function audit_table(Detailed error mentioned below). I have below questions. 

Q1) As i understand the schema for postgresql-audit is not getting created in my local setup.What script/command to trigger to generate postgresql-audit schema(triggers/tables) in my local setup? 
Q2) From documentation, it seems like adding     __versioned__ = {} in the model should enable audit entries. Is there any other step required to enable audit on sql-alchemy models?
 
`
import random

from postgresql_audit import versioning_manager
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import session
from sqlalchemy.testing import db

from common.connectors.db_executor import DBUpdateExecutor
from store.connectors.sqlalchemy_metadata import Base
from sqlalchemy import select

versioning_manager.init(Base)

class Article(Base):
    __tablename__ = 'article'
    __versioned__ = {}
    id = Column(Integer, primary_key=True)
    name = Column(String)

article = Article(id = random.randint(0, 100), name='Some article')
executor = DBUpdateExecutor()
_ = executor.get_db_connection()
executor.insert_record(article)


Activity = versioning_manager.activity_cls

SessionLocal = executor.get_local_session()

db = SessionLocal()

db.execute('''SELECT audit_table('article')''')

db.query(Activity).first()


activity.id             # 1
activity.table_name     # 'article'
activity.verb           # 'insert'
activity.old_data       # {}
activity.changed_data   # {'id': '1', 'name': 'Some article'}
`
Error: 
###
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function audit_table(unknown) does not exist
LINE 1: SELECT audit_table('article')
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mainaksethi/Documents/singulr_pycharm2/singulr-main/ai-trust-db/store/data_models/Article.py", line 32, in <module>
    db.execute('''SELECT audit_table('article')''')
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/miniconda3/envs/ai-trust-db/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function audit_table(unknown) does not exist
LINE 1: SELECT audit_table('article')
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT audit_table('article')]
(Background on this error at: https://sqlalche.me/e/14/f405)
###

**Comment by tvuotila** [comment]
> Q1) As i understand the schema for postgresql-audit is not getting created in my local setup.What script/command to trigger to generate postgresql-audit schema(triggers/tables) in my local setup?

I used following command to create all tables and triggers:
```
Base.metadata.create_all(engine)
```
Where `engine` was `engine = create_engine("postgres://localhost/tvuotila", echo=True)`.

In production environment, I would use something like [Alembic](https://alembic.sqlalchemy.org/en/latest/).

> Q2) From documentation, it seems like adding versioned = {} in the model should enable audit entries. Is there any other step required to enable audit on sql-alchemy models?

Audit entries are created with database triggers. Thus, the `SELECT audit_table('article')` is needed, but Alembic or another database migration tool should create the necessary database migration automatically.

**Comment by mainak-singulr** [comment]
Thanks @tvuotila . That worked for me.
