### ISSUE TITLE
This one or SQLAlchemy-Continuum?

### ISSUE THREAD

**Issue by jmagnusson** [kvesteri/postgresql-audit#3]
Hi Finnish neighbor!

Considering you wrote both - Would you recommend to use this project or `SQLAlchemy-Continuum`? Assuming all prerequisites are fulfilled.

I'm guessing `postgresql-audit` would be the one to choose if you don't care for revert functionality... Right? :blush: 

Thanks,
Jacob

**Comment by kvesteri** [comment]
Hi there! 

I would use this one considering its an order of magnitude faster and more simple. Implementing revert to PostgreSQL-Audit is a huge task but its definitely something I've had in mind for a long time.

**Comment by jmagnusson** [comment]
Okay thanks for clarifying this!

I can see that the schema `audit` is hard-coded. Is there any special reason for this? My alembic migration fails because this schema doesn't exist. (I guess I could create it but I'm just curious to know why).

**Comment by kvesteri** [comment]
No reason, there should definitely exist a variable configuring that.

**Comment by kvesteri** [comment]
Thanks for the PR, I think however that rather than completely removing the schema we should make it configurable. If ``None`` value is given for that configuration variable then no schema should be used.

**Comment by jmagnusson** [comment]
Hmm okay. What's the use case for having a separate schema? Isn't it more convenient to just keep it together with the rest of your app's codebase?

I don't know your code well enough to find a good entry point for this configuration option.

**Comment by kvesteri** [comment]
Schemas are like namespaces, very good for avoiding naming collisions and structuring your database. http://stackoverflow.com/questions/5678902/postgresql-schemas-usage-scenario-case/13206645#13206645

You can add the variable as a constructor parameter for VersioningManager (there is already one configurable parameter there actor_cls).

**Comment by jmagnusson** [comment]
Yeah I guess it could be useful in a really large project. I'll see what I can do.

Sorry for the myriad of questions, but I hope this will be the last one for now. I do some tests with my codebase that uses SQLite instead of PostgreSQL. The bind to my declarative base is created after all the models have been associated with it. From what I've understood I have to call `versioning_manager.init(Base)` before the models have been declared. Because of this I don't really know how to avoid this error:

```python
    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: activity [SQL: 'UPDATE activity SET client_addr=?, actor_id=? WHERE activity.transaction_id = txid_current() AND activity.issued_at > CURRENT_TIMESTAMP - ?'] [parameters: (None, None, '1970-01-02 00:00:00.000000')]
```

Is there any way we could make `postgresql-audit` not act at all if the bind is a non-PostgreSQL database? OR can I somehow initialize the `versioning_manager` after the binding has occurred?

**Comment by kvesteri** [comment]
Why are you testing this with SQLite? The error you are getting comes from the after_flush listener that PostgreSQL-Audit uses, which in turn calls ``set_activity_values`` function (see: https://github.com/kvesteri/postgresql-audit/blob/master/postgresql_audit/base.py#L178).

**Comment by jmagnusson** [comment]
I don't want to test postgresql-audit with SQLite, but one of my app's unit tests contains some parts which are tested with SQLite. So that's why I'm asking for some way to disable postgresql-audit.

**Comment by kvesteri** [comment]
You can disable to listeners by calling ``versioning_manager.remove_listeners()`` and then re-attach them by calling ``versioning_manager.attach_listeners()``

**Comment by jmagnusson** [comment]
Yeah I guess that would be one option. I did it this way though: https://github.com/jmagnusson/postgresql-audit/commit/21f9fc2c2cb7b68c4168119fe84d9d04a4d7c25e

**Comment by piotr-dobrogost** [comment]
I'm curious what made you create another library just for Postgresql? Why not using triggers for greater speed in Continuum and keep one API user-side? This would make Continuum versatile and fast library, a go-to library for versioning/audit for all SQLAlchemy users no matter what backend db is being used.

**Comment by kvesteri** [comment]
Well I'm planning to change the scope and name of that project to something more general. The fact was that when I started that project PostgreSQL was the only database with good JSON support. Now other databases are catching up as well and I could add support for those.

The fundamental difference is that PostgreSQL-Audit uses one table for versioning with no schema reflection (everything is just dumped in JSONB columns). Thus it is much easier to keep things fast. The triggers currently used in Continuum are much more complex.
